#include "src/cliproxy.cpp"
#include "src/command.cpp"
#include "src/command_table.cpp"
#include "src/common.cpp"
#include "src/image.cpp"
#include "src/mat.cpp"
#include "src/ros_interface.cpp"
#include "src/serialize.cpp"
#include "src/soar_interface.cpp"
#include "src/visual_matching.cpp"
#include "base64/base64.cpp"
#include "src/svs.cpp"

#include "src/spatial_scene/drawer.cpp"
#include "src/spatial_scene/filter.cpp"
#include "src/spatial_scene/filter_input.cpp"
#include "src/spatial_scene/filter_table.cpp"
#include "src/spatial_scene/sgnode.cpp"
#include "src/spatial_scene/sgnode_algs.cpp"
#include "src/spatial_scene/scene.cpp"

#include "src/commands/add_node.cpp"
#include "src/commands/extract.cpp"
#include "src/commands/set_transform.cpp"
#include "src/commands/set_tag.cpp"
#include "src/commands/delete_tag.cpp"
#include "src/commands/copy_node.cpp"
#include "src/commands/copy_transform.cpp"
#include "src/commands/delete_node.cpp"

#include "src/filters/axis_distance.cpp"
#include "src/filters/axis_relation.cpp"
#include "src/filters/base_node_filters.cpp"
#include "src/filters/calculate_placement.cpp"
#include "src/filters/contain.cpp"
#include "src/filters/distance.cpp"
#include "src/filters/intersect.cpp"
#include "src/filters/monitor_object.cpp"
#include "src/filters/node.cpp"
#include "src/filters/occlusion.cpp"
#include "src/filters/overlap.cpp"
#include "src/filters/tag_select.cpp"
#include "src/filters/volume.cpp"

#include "src/vwm/visual_buffer.cpp"
#include "src/vwm/visual_operation.cpp"
#include "src/vwm/visual_operation_graph.cpp"
#include "src/vwm/visual_working_memory.cpp"

#include "src/commands/vwm_add_vop_node.cpp"
#include "src/commands/vwm_edit_vop_node.cpp"
#include "src/commands/vwm_load_percept.cpp"
#include "src/commands/vwm_save_percept.cpp"
#include "src/commands/vwm_set_file.cpp"

#include "src/vltm/exact_visual_archetype.cpp"
#include "src/vltm/visual_long_term_memory.cpp"

#include "src/commands/vwm_flip_percept.cpp"
#include "src/commands/vwm_get_vision.cpp"
#include "src/commands/vwm_match_percept.cpp"
#include "src/commands/vwm_move_percept.cpp"
#include "src/commands/vwm_recall.cpp"
#include "src/commands/vwm_remember_percept.cpp"
#include "src/commands/vwm_remove_percept.cpp"
#include "src/commands/vwm_rotate_percept.cpp"
#include "src/commands/vwm_translate_percept.cpp"
